book/urls.py
from .views import book_table
from django.urls import path


urlpatterns = [
    path('book/', book_table, name='book'),  # Booking a table
]

order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('history/', views.order_history, name='order_history'),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('user.urls')),
    path('', include('cart.urls')),
    path('', include('checkout.urls')),
    path('', include('order.urls')),
    path('', include('book.urls')),
    path('', include('search.urls')),
    path('', include('report.urls')),
    path('', include('chatbox.urls')),
]

order/models.py
from django.db import models
from user.models import Customer
from home.models import Dish
# Create your models here.

class Order(models.Model):
    user_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    total_price = models.DecimalField(decimal_places=2, max_digits=10)
    order_date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)


class OrderDetails(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    dish_id = models.ForeignKey(Dish, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    unit_price = models.DecimalField(max_digits=5, decimal_places=2)

    def total_price(self):
        return self.quantity * self.unit_price

order/views.py
from django.shortcuts import render
from .models import Order, OrderDetails
# Create your views here.

def order_history(request):
    customer = request.user  # Nếu bạn sử dụng hệ thống auth
    orders = Order.objects.filter(user_id=customer).order_by('-order_date')

    return render(request, 'order/order_history.html', {'orders': orders})

templates/order/order_history.html
<h2>Lịch sử mua hàng</h2>

{% for order in orders %}
    <div class="order">
        <h3>Ngày: {{ order.order_date }}</h3>
        <p>Tổng giá: {{ order.total_price }} - Trạng thái: {{ order.get_status_display }}</p>

        <table>
            <thead>
                <tr>
                    <th>Tên món</th>
                    <th>Số lượng</th>
                    <th>Đơn giá</th>
                    <th>Tổng tiền</th>
                </tr>
            </thead>
            <tbody>
                {% for item in order.orderdetails_set.all %}
                <tr>
                    <td>{{ item.dish_id.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.unit_price }}</td>
                    <td>{{ item.total_price }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endfor %}